### ISSUE TITLE
Klasse-C.ipynb: FileNotFoundError

### ISSUE THREAD

**Issue by defermelowie** [jangenoe/InteractieveCursus#2]
In de notebook over Klasse C versterkers kan onderstaande cell niet succesvol uitgevoerd worden omdat de file `simul/classC.print` niet gevonden wordt / bestaat.

```python
spice=pd.read_fwf('simul\classC.print', comment='*', skiprows=4, sep=' ')
spice.plot(x='time',y=['v(2)', 'v(4)'], figsize=(8,6),fontsize=10,xlim=(0,0.00001));
```
Error message:

```Python
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-6-760071fd9be0> in <module>
----> 1 spice=pd.read_fwf('simul\classC.print', comment='*', skiprows=4, sep=' ')
      2 spice.plot(x='time',y=['v(2)', 'v(4)'], figsize=(8,6),fontsize=10,xlim=(0,0.00001));

FileNotFoundError: [Errno 2] No such file or directory: 'simul\\classC.print'
```

**Comment by jangenoe** [comment]
Dank je voor de input. Ondertussen is dit veranderd.
In plaats van de spice output files plaats ik nu de spice input files. Dit is veel compacter en laat ook gemakkelijk toe nieuwe dingen te proberen.
Hiervoor dien je wel PySpice geïnstalleerd te hebben en ook de link met de simulator moet actief zijn.

Deze notebooks zijn pas recent toegevoegd en het blijft werk in progress. Alle  nieuwe inputs zijn dus zeer welkom.
